### PR TITLE
Enable dynamic starting room

### PR DESCRIPTION
**Pull request by vickean**
I've done some small changes to the world.py and game.py files to allow custom StartingRoom positions within map.txt. This should open up the option for custom maps to be made and played with without having to worry about the starting coordinates assigned within the Player class.

This is my first time using GitHub as a beginner python programmer, any advice and comments are greatly appreciated. 

Have fun!!

### CODE REVIEW

**Comment by phillipjohnson** [comment]
Hi Victor,

Thanks for the pull request. This is a good idea, I think it would make the program more flexible. I have some suggestions on your implementation.

 1. There doesn't seem to be much use in storing `_game_map`. Why not just record the starting position during the parsing of the map when the StartingRoom is encountered?
 2. The `Player` class current initializes the player's position, but you're moving that into the game. the player's position should be initialized in just one place. I don't have an opinion on where, but having two player location initializations is confusing.

Feel free to make another commit and I can review the changes. Thanks!

**Comment by vickean** [comment]
Hi Phillip,

Thanks for taking the time to read through my changes. I've taken your suggestions into consideration and have made some changes to the program. 

I've actually re-written your source for this tutorial in python 2 instead of just forking it. The commits here are copied from my repo with the ported source. The reason being I've just finished the python course from codecademy which was based on python 2. 

In your opinion, would it be a good idea for me to move to python 3 or remain in python 2 as a beginner?

**Comment by phillipjohnson** [comment]
I've looked over these updates and everything looks good except for the variable name change I suggested. Once that's corrected, I should be able to merge these changes in. To be clear, you are OK with me updating the tutorial to match these changes, correct?

As for Python 2 vs 3, I don't see any reason to stick with 2. Python 3 came out in 2008! If you absolutely need to use a library that is only 2.7 compatible, then you have to use Python 2. But for the vast majority of projects, Python 3 is going to be fine.

**Comment by vickean** [comment]
OK. The variable name has been changed. Go right ahead with the tutorial update. I think it would be a good example of how the 'starting_position' variable can be defined as a Global variable which can be accessed from outside the function. It's something new and useful that I've learned and would love to share it with other beginners. 

Will make another pull request when I have time to make more changes. Thanks again for the info and advice! =)

**Pull request merged**
